In [ ]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
import matplotlib.pyplot as plt
#Importing our data file
raw_data = pd.read_csv('Car_Purchasing_Data.csv', delimiter = ',')
raw_data.head()


#Creating a copy
data = raw_data.copy()

#Removing columns with string values
​
data_no_string = data.iloc[:, 3:8]
data_no_string.head()


#Tranforming our age data into dummies, since we have alot of different ages values it is better to categorize these age values
age_dummies = pd.get_dummies(data_no_string['Age'])
age_dummies


#Confirming sum of each row to make sure 1 values exists in all rows
age_dummies['check'] = age_dummies.sum(axis=1)


age_dummies = age_dummies.drop(['check'], axis=1)
age_dummies.info()


#Divding the age categories into differnt columns
age_dummies_1 = age_dummies.iloc[:, 0:9].max(axis=1)
age_dummies_2 = age_dummies.iloc[:, 10:19].max(axis=1)
age_dummies_3 = age_dummies.iloc[:, 20:29].max(axis=1)
age_dummies_4 = age_dummies.iloc[:, 30:42].max(axis=1)


#Combining the columns togther with concat method
df_concat = pd.concat([data_no_string, age_dummies_1, age_dummies_2, age_dummies_3, age_dummies_4], axis=1)

df_concat.columns.values

new_columns = ['Gender', 'Age', 'Annual Salary', 'Credit Card Debt', 'Net Worth',
       'Age20-33', 'Age34-43', 'Age44-53', 'Age54-70']

df_concat.columns = new_columns
df_concat.columns


#Remove the original Age column from the dataset. Since we categorized the age
df_concat = df_concat.drop(['Age'], axis=1)


#Scaling the data & Shuffling them
scale_data = preprocessing.scale(df)

shuffle = np.arange(scale_data.shape[0])
np.random.shuffle(shuffle)


#The preprocessing phase is done; now in  a new Notebook we will create our model
import numpy as np
import pandas as pd
import sklearn
from sklearn import preprocessing
from sklearn.model_selection import train_test_split


#Importing the data
raw_data = pd.read_csv("car-preprocessed.csv", delimiter=',')
data = raw_data.copy()

#Finding the Median of our data
data['Annual Salary'].median()

#Creating our targets below based on our median 
#Based on this dataset, I think Annual salary is the best feature to set as target to make our predictions

targets = np.where(data['Annual Salary'] > 
                    data['Annual Salary'].median(), 1,0)

data['People purchased'] = targets


#Using the logistic regression 
#Splitting our data into train & test data

from sklearn.linear_model import LogisticRegression
from sklearn import metrics


x_train, x_test, y_train, y_test = train_test_split(data_no_targets, targets, train_size=0.9)


model = LogisticRegression()


#Fit the model
model.fit(x_train,y_train)


#Finding our intercept
model.intercept_
array([-0.3746957])


#Finding our coefficient 
model.coef_
array([[-2.34936767e-01,  6.49301455e+00,  9.46706818e-02,
         3.31499873e-03, -1.63245065e-02,  3.17489069e-02,
         3.02199770e-01, -4.86391073e-02]])



#Testing our model accuracy with the below
model.score(x_test,y_test)
0.94


#Inserting a new data to be predicted
new_data = [[0.988071, 0.712361, 0.2213, 0.465, -0.3223,-0.8723,-0.44532, 0]]
model.predict(new_data)
array([1])


#Saving the model to export it for other users
import pickle

with open('Sales Model', 'wb')as file:
    pickle.dump(model, file)